services:
  - type: web
    name: cexcie-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cexcie-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: cexcie-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cexcie-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: cexcie-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: cexcie-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cexcie-db
          property: password

databases:
  - name: cexcie-db
    databaseName: cexcie_dashboard
    user: cexcie_user 